### PR TITLE
Add drawio embed mode

### LINKED ISSUE #61: Use embed mode
I think we don't use the standardized messaging protocol this library provides for embedding in other applications, to make the save menus seamless, etc. It would be great to look into using the embed mode: https://desk.draw.io/support/solutions/articles/16000042544-embed-mode

### PR DESCRIPTION
**Pull request by bollwyvl**
[Binder](https://mybinder.org/v2/gh/bollwyvl/jupyterlab-drawio/add-drawio-embed-mode?urlpath=lab%2Ftree%2Ftestfiles%2FTestFile.dio)

- fixes #61 

Welp, here's something to look at. The [list of changes](https://github.com/QuantStack/jupyterlab-drawio/issues/61#issuecomment-635048588) from my initial push for a demo is... large. I just bumped it up to the drawio release that came out... this afternoon, and haven't tested it thoroughly, but would like to start the dialog about getting this in.

I've been using it for some work projects, and it pretty much does the job. My biggest complaint is that it isn't possible to do any kind of "live" reformatting of the XML to be more git/text editor-friendly (as it uses calculated etags), so I've been doing that in a formatting script. Of course, the diff isn't very pretty, and it uses ordinal ids, which makes merging mostly impossible, but it's _something_!

### CODE REVIEW

**Comment by bollwyvl** [comment]
Hey, folks! An update: I've been tinkering with an [even _crazier_ branch](https://github.com/bollwyvl/jupyterlab-drawio/tree/add-drawio-export) which adds:
- diagrams embedded inside ipynb
  - the good
    - the workflow is really quite nice: make a plot (preferably in svg), drag it into drawio, save clears the dirty state on both dockpanel items.
  - the bad
    - some weirdness due to "special" things that happen around notebook paths/contents in lab
    - dragging rendered markdown in... works... but lots of things are weird (text gets theme-derived styling)
    - text wrap not so good 
- PDF export
  - the good
    - a prototype ipywidgets toolchain for combining multiple drawio files (`dio`, `png`, `svg`, or `ipynb`) into one PDF
     - supports jinja templates
     - embeds (composite) drawio XML into generated PDFs
  - the bad
    - links don't work
    - no metadata tagging (e.g. outline)
    - nodejs, puppeteer, chromium on the server... perhaps if the nbconvert/pyppeteer stuff gets a little more robust, i can piggyback off that
    - while connecting the nodejs stuff with jupyter-server-proxy is pretty easy, it might be better as dedicated serverextension

Next steps:
- after having demoed this a few times: there's always that guy that says, _so why doesn't the plot update?_
  - the thought is to write a drawio plugin which exposes all of the rendered markdown and outputs inside drawio so they can be updated whenever their "parent" object changes... the above linked drawio issue points to some of the issues I'm encountering. 
    - ideally, the plugin would be pretty lightweight (e.g. not introduce a new geometry, as that would drastically reduce the portability) but instead just use some metadata
    - `JUPYTERLAB_DRAWIO_CELL_NAME` would be the cell [`name`](https://github.com/jupyter/nbformat/blob/master/nbformat/v4/nbformat.v4.4.schema.json#L138)
    - `JUPYTERLAB_DRAWIO_CELL_PART` would be either `source` or `outputs`
    - `JUPYTERLAB_DRAWIO_CELL_OUTPUT` would be a number
    - `JUPYTERLAB_DRAWIO_CELL_OUTPUT_MIME` would be the mime bundle key to pick off, and then encode
- using pdfjs to make the roundtrip even more seamless, e.g. `Drawing.dio.pdf`, for the price of a slower save, would always be up-to-date with what you last saved

**Comment by wolfv** [comment]
this is awesome!

**Comment by bollwyvl** [comment]
Hey, y'all: I know your team is super busy... I've been advocating for (and using) mamba quite a bit :heart_eyes: , and don't even have anything to complain about yet (you know I would if i did). But I've been getting a lot of use out of my various branches off this repo, and am considering publishing some pre-releases, probably under @deathbeds.

The goals motivating this:

- deeper notebook integration (e.g. syncing outputs) needs to be its own package
- some of the drawio plugins (which we can start using now that they fixed some path stuff) I want need to be their own packages (e.g. multi-mb autolayout packages with WebWorkers)
- using [jupyterlab-videochat](https://github.com/yuvipanda/jupyter-videochat) to backhaul drawio's collaborative editing over jitsi's XMPP pipe needs to be its own package
- testing/CI in anger
- re-doing the PDF export in python as an nbconvert or serverextension

As my forks are, in a not-even-that-mergeable-upstream state, it's kinda hard (and slow) to be sub-moduling them into the tools/demos where I want to try things and re-building them everywhere: real (pre)releases of this crazy stuff would make it a lot more robust.

I'm still very much interested in getting these features to users of this extension... and the name and licensor changes, keeping it BSD-3-Clause, would be revertible in the future, but there will probably be a fair amount of infrastructure changed (probably `lerna`, `doit`, `robotframework`, etc.) to start helping me stay sane while working. These might be too many opinions to introduce to this repo. But hackers gotta hack...

**Comment by wolfv** [comment]
@bollwyvl thanks for all the nice words, and for advocating mamba! It's true that I am putting most of my time into that project right now, so that too little is left to get jupyterlab-drawio where it should be. 
I am totally happy to make you the responsible person for the future of this extension! :) lets check what @SylvainCorlay has to say. 
Would you want to keep it under QuantStack or should we figure out a way to move it to one of the Jupyter orgs?

**Comment by bollwyvl** [comment]
A lot of good points!

I'm not looking for another _job_ right now, I just want some
probably-broken releases that I can do janky demos with.

I think drawio represents an excellent opportunity for meeting a lot of
Jupyter user and community needs, and as an upstream, they've been
extremely responsive and transparent. So, if we can show some of the
features described above, I think we should try to get it added someplace
more official.

Given its size, though, I don't see it going into a core offering any time
soon, but maybe if we start pushing on some more Jupyter "prebuilt"
distributions, maybe it goes into some of those.

**Comment by bollwyvl** [comment]
I've got the first of those pre-releases up over at https://github.com/deathbeds/jupyterlab-drawio.

Onward!

**Comment by bollwyvl** [comment]
Hey folks: I just dropped `ipydrawio v1.0.0a0`, which includes this work... guess I'm going to close this one!

**Comment by wolfv** [comment]
Hey @bollwyvl thats awesome. Sorry for not having enough time to give this the attention it deserves :(

**Comment by bollwyvl** [comment]
No worries... Only so much wolf to go around, and the other stuff you folks
are working is amazing, as always.

A good thing now, since they don't share any names/tokens, is one can
install both and evaluate them together.

Anyhow, some of the next directions over there I'm looking forward to
- seeing if diagrams can be made collaborative with  jupyter-videochat
0.5.0, which now also exposes more of its inner workings... Jitsi has some
apis to expose more of the underlying xmpp stream, which is well and good
enough for a little xml
- seeing if I can get web standard outputs to sync between a notebook and
(its metadata-embedded) drawio
- building some jupyterlab mockup templates

You know I'm always up to jam with you guys... It's been a while!

**Comment by wolfv** [comment]
@bollwyvl you should come to our chat! we are working on adding collaborative editing to jupyterlab, and one of the potential showcase extensions will be jlab-drawio :) We're going to use Y.js and we're funded for this work. It's going to be quite amazing.

**Comment by bollwyvl** [comment]
Welp... having been down the RTC road a [couple](https://github.com/nrbgt/derby-notebook) [times](https://github.com/deathbeds/jupyterlab-dat), it's a really awesome when it works!

My thinking on the jitsi/dio piece: multi-user collaborative drawing is a proven, useful activity, that would benefit teams i work with _right now_. Full-fat drawio has its own (as you can no doubt imagine, home-rolled) mechanism for doing file sync which very well might _just work_ with the pipe offered up by jitsi, which would improve the utility of _both_ of them as extensions. I'm basically trying to invent as little as possible these days, and integrate with the best stuff I can, leaving as many API hooks open as possible.

The ugly parts of my experiences: the general semi-structured case (like a notebook) is... hard. Handling trust and identity is... hard, especially if federated. Fine-grained permissions is... really hard. Handling shared compute is... not something i have tackled as _server_ thing, much less a decentralized thing, and don't even know what that would mean. yjs is a solid play, for sure, if something needs to be built from the ground up.... and the team has already solved all those things. I was impressed at how well it worked with prosemirror.

**Pull request closed without merging**
