### PR TITLE
update for jupyterlab 1.0.0

### PR DESCRIPTION
**Pull request by wolfv**

### CODE REVIEW

**Comment by jtpio** [comment]
Tested locally, seems to be working fine :+1: 

image

**Comment by wolfv** [comment]
same here!

**Comment by wuhuanhost** [comment]
Node v8.11.4

> "d:\Program Files\nodejs\npm.CMD" pack jupyterlab-drawio
jupyterlab-drawio-0.5.0.tgz

Fetching URL: https://registry.npmjs.org/jupyterlab-drawio
Fetching URL: https://registry.npmjs.org/jupyterlab-drawio
Traceback (most recent call last):

  File "d:\program files\python37\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

  File "d:\program files\python37\lib\site-packages\jupyterlab\labextensions.py", line 82, in start
    ans = self.run_task()

  File "d:\program files\python37\lib\site-packages\jupyterlab\labextensions.py", line 103, in run_task
    for arg in self.extra_args

  File "d:\program files\python37\lib\site-packages\jupyterlab\labextensions.py", line 103, in <listcomp>
    for arg in self.extra_args

  File "d:\program files\python37\lib\site-packages\jupyterlab\commands.py", line 316, in install_extension
    return handler.install_extension(extension)

  File "d:\program files\python37\lib\site-packages\jupyterlab\commands.py", line 517, in install_extension
    info = self._install_extension(extension, tempdir)

  File "d:\program files\python37\lib\site-packages\jupyterlab\commands.py", line 1416, in _install_extension
    raise ValueError(msg)

ValueError: This extension does not yet support the current version of JupyterLab.


Conflicting Dependencies:
JupyterLab              Extension      Package
>=1.0.0 <2.0.0          >=0.19.1 <0.20.0@jupyterlab/application
>=1.0.0 <2.0.0          >=0.19.1 <0.20.0@jupyterlab/apputils
>=3.0.0 <4.0.0          >=2.0.2 <3.0.0 @jupyterlab/coreutils
>=1.0.0 <2.0.0          >=0.19.1 <0.20.0@jupyterlab/filebrowser
>=1.0.0 <2.0.0          >=0.19.1 <0.20.0@jupyterlab/launcher

Exiting application: jupyter

**Comment by wuhuanhost** [comment]
> Tested locally, seems to be working fine 👍
> 
> image

Node v8.11.4

> "d:\Program Files\nodejs\npm.CMD" pack jupyterlab-drawio
jupyterlab-drawio-0.5.0.tgz

Fetching URL: https://registry.npmjs.org/jupyterlab-drawio
Fetching URL: https://registry.npmjs.org/jupyterlab-drawio
Traceback (most recent call last):

  File "d:\program files\python37\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

  File "d:\program files\python37\lib\site-packages\jupyterlab\labextensions.py", line 82, in start
    ans = self.run_task()

  File "d:\program files\python37\lib\site-packages\jupyterlab\labextensions.py", line 103, in run_task
    for arg in self.extra_args

  File "d:\program files\python37\lib\site-packages\jupyterlab\labextensions.py", line 103, in <listcomp>
    for arg in self.extra_args

  File "d:\program files\python37\lib\site-packages\jupyterlab\commands.py", line 316, in install_extension
    return handler.install_extension(extension)

  File "d:\program files\python37\lib\site-packages\jupyterlab\commands.py", line 517, in install_extension
    info = self._install_extension(extension, tempdir)

  File "d:\program files\python37\lib\site-packages\jupyterlab\commands.py", line 1416, in _install_extension
    raise ValueError(msg)

ValueError: This extension does not yet support the current version of JupyterLab.


Conflicting Dependencies:
JupyterLab              Extension      Package
>=1.0.0 <2.0.0          >=0.19.1 <0.20.0@jupyterlab/application
>=1.0.0 <2.0.0          >=0.19.1 <0.20.0@jupyterlab/apputils
>=3.0.0 <4.0.0          >=2.0.2 <3.0.0 @jupyterlab/coreutils
>=1.0.0 <2.0.0          >=0.19.1 <0.20.0@jupyterlab/filebrowser
>=1.0.0 <2.0.0          >=0.19.1 <0.20.0@jupyterlab/launcher

Exiting application: jupyter

**Comment by wuhuanhost** [comment]
The juputer-drawio package on NPM is not updated?

`jupyter labextension install jupyterlab-drawio`  Installation prompts for the following errors

Node v8.11.4

> "d:\Program Files\nodejs\npm.CMD" pack jupyterlab-drawio
jupyterlab-drawio-0.5.0.tgz

Fetching URL: https://registry.npmjs.org/jupyterlab-drawio
Fetching URL: https://registry.npmjs.org/jupyterlab-drawio
Traceback (most recent call last):

  File "d:\program files\python37\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

  File "d:\program files\python37\lib\site-packages\jupyterlab\labextensions.py", line 82, in start
    ans = self.run_task()

  File "d:\program files\python37\lib\site-packages\jupyterlab\labextensions.py", line 103, in run_task
    for arg in self.extra_args

  File "d:\program files\python37\lib\site-packages\jupyterlab\labextensions.py", line 103, in <listcomp>
    for arg in self.extra_args

  File "d:\program files\python37\lib\site-packages\jupyterlab\commands.py", line 316, in install_extension
    return handler.install_extension(extension)

  File "d:\program files\python37\lib\site-packages\jupyterlab\commands.py", line 517, in install_extension
    info = self._install_extension(extension, tempdir)

  File "d:\program files\python37\lib\site-packages\jupyterlab\commands.py", line 1416, in _install_extension
    raise ValueError(msg)

ValueError: This extension does not yet support the current version of JupyterLab.


Conflicting Dependencies:
JupyterLab              Extension      Package
>=1.0.0 <2.0.0          >=0.19.1 <0.20.0@jupyterlab/application
>=1.0.0 <2.0.0          >=0.19.1 <0.20.0@jupyterlab/apputils
>=3.0.0 <4.0.0          >=2.0.2 <3.0.0 @jupyterlab/coreutils
>=1.0.0 <2.0.0          >=0.19.1 <0.20.0@jupyterlab/filebrowser
>=1.0.0 <2.0.0          >=0.19.1 <0.20.0@jupyterlab/launcher

Exiting application: jupyter

**Comment by SylvainCorlay** [comment]
@dreamer the latest release of jupyterlab-drawio requires jupyterlab 1.0

**Comment by wolfv** [comment]
yep, but we also haven't pushed it to npm yet. will do it now!

**Comment by wolfv** [comment]
uploaded 0.6.0 to npm now!

**Pull request merged**
