### PR TITLE
Support JupyterLab 2.0.0

### LINKED ISSUE #51: Support JupyterLab 2.0.0
JupyterLab 2.0.0 is out, and this extension have conflicting dependencies with its core packages.

```
Conflicting Dependencies:
JupyterLab              Extension      Package
>=2.0.0 <2.1.0          >=1.0.0 <2.0.0 @jupyterlab/application
>=2.0.0 <2.1.0          >=1.0.0 <2.0.0 @jupyterlab/apputils
>=4.0.0 <4.1.0          >=3.0.0 <4.0.0 @jupyterlab/coreutils
>=2.0.0 <2.1.0          >=1.0.0 <2.0.0 @jupyterlab/filebrowser
>=2.0.0 <2.1.0          >=1.0.0 <2.0.0 @jupyterlab/launcher
```

## References
- [Change log for developers](https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html#for-developers)
- [A migration guide](https://jupyterlab.readthedocs.io/en/stable/developer/extension_migration.html#extension-migration)

### PR DESCRIPTION
**Pull request by consideRatio**
Fixes #51.

After this PR is merged, future releases of this extension will now require JupyterLab 2, but if JupyterLab 1 is used an old versions of this package can still be used automatically instead.

### CODE REVIEW

**Comment by jasongrout** [comment]
I think it is fine to only support jlab 2 moving forward.

**Comment by consideRatio** [comment]
@jasongrout can you help me validate my understanding:

Assume we have a NPM package with two versions, version 0.1 with JupyterLab 1 dependencies, and version 0.2 with JupyterLab 2 dependencies. If I had JupyterLab 1 installed, and did `jupyter labextension install <name>`, it would install version 0.1 that was compatible even though 0.2 is out only because it would be incompatible?

**Comment by jasongrout** [comment]
>  it would install version 0.1 that was the latest version compatible with JupyterLab 1 dependencies?

Yes. JupyterLab is smart enough to go back through the published versions of a package and install the latest compatible version.

**Comment by granitDev** [comment]
As a user of Jupyter Labs, I would like to request this pull request be merged in as soon as possible. I would like to have this functionality back in version 2.

Thank you.

**Comment by jasongrout** [comment]
CC @wolfv

**Comment by wolfv** [comment]
Thanks everyone!

**Comment by consideRatio** [comment]
Thanks @wolfv!

This will be part of a release > 0.6.0: https://www.npmjs.com/package/jupyterlab-drawio

**Pull request merged**
