### PR TITLE
Update for JLab 0.33.X

### PR DESCRIPTION
**Pull request by timkpaine**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
From gitter

@SylvainCorlay:
> why renaming `_handleDirtyState` into `_handleDirtyStateNew`? (and `_onModelStateChanged` to `_onModelStateChangedNew`)

#@timkpaine
> `_handleDirstState` is a private method of `DocumentWidget` now.
> I think that functionality was pulled out into the base class but I didnt know exactly what its doing, so I didnt want to mess too much and you can't super into it because its private

**Comment by blink1073** [comment]
This patch on top of this PR makes this package work with Jlab 0.34.0rc0 (just bumping the dep versions):

```diff
diff --git a/package.json b/package.json
index 4a53542..c6a1bc9 100644
--- a/package.json
+++ b/package.json
@@ -30,13 +30,13 @@
     "watch": "tsc -w"
   },
   "dependencies": {
-    "@jupyterlab/application": "^0.17.2",
-    "@jupyterlab/apputils": "^0.17.2",
+    "@jupyterlab/application": "^0.18.0",
+    "@jupyterlab/apputils": "^0.18.0",
     "@jupyterlab/coreutils": "^2.0.2",
-    "@jupyterlab/docregistry": "^0.17.2",
-    "@jupyterlab/filebrowser": "^0.17.3",
-    "@jupyterlab/launcher": "^0.17.2",
-    "@jupyterlab/mainmenu": "^0.6.2"
+    "@jupyterlab/docregistry": "^0.18.0",
+    "@jupyterlab/filebrowser": "^0.18.0",
+    "@jupyterlab/launcher": "^0.18.0",
+    "@jupyterlab/mainmenu": "^0.7.0"
   },
   "devDependencies": {
     "rimraf": "^2.6.1",
```

**Comment by SylvainCorlay** [comment]
Could you reproduce the issue with 0.33?

**Comment by blink1073** [comment]
Nope, worked fine with this PR...

**Pull request merged**
