### PR TITLE
Update for JupyterLab 0.32.

### PR DESCRIPTION
**Pull request by jasongrout**
CC @wolfv.

Test using 

```bash
pip install --pre jupyterlab # to get the 0.32 RC.
jupyter labextension install ./path/to/this/repo
```

### CODE REVIEW

**Comment by jasongrout** [comment]
If this is released before Tuesday, there's a chance @fperez might demo it in a talk...

**Comment by wolfv** [comment]
Thanks Jason!
That should work out for Tuesday! :)

**Comment by fperez** [comment]
Please ping me directly - my Tuesday will be very busy but I can probably pull a quick update at the end.

**Comment by jasongrout** [comment]
@wolfv - if you give me permissions, I'm also happy to push this release.

**Pull request merged**
